services:
  db:
    image: postgres:15
    container_name: pexels_postgres
    restart: always
    environment:
      POSTGRES_USER: pexels_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: pexels_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: