version: '3.8'

services:
  redis-server:
    image: redis:latest
    command: ["redis-server", "--requirepass", "ganhteamgg123"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./webimage
      dockerfile: Dockerfile
    env_file:
      - ./webimage/.env
    volumes:
      - ./webimage:/app
      - clip-cache:/root/.cache/clip  
    ports:
      - "8000:8000"
    depends_on:
      - redis-server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    environment:
      - WATCHPACK_POLLING=true  
    depends_on:
      - backend

volumes:
  redis-data:
  clip-cache:  