# version: '3.8'

services:
  redis-server:
    image: redis:latest
    command: ["redis-server", "--requirepass", "ganhteamgg123"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./webImage
      dockerfile: Dockerfile
    env_file:
      - ./webImage/.env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*,localhost,127.0.0.1
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ganhteamgg123
    volumes:
      - ./webImage:/app
      - clip-cache:/root/.cache/clip  
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
      - /app/.next
      - /app/.swc
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - TAILWIND_MODE=watch
    depends_on:
      - backend
    command: sh -c "npm run dev"

volumes:
  redis-data:
  clip-cache:
