  version: '3.8'

  services:
    redis-server:
      image: redis:latest
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-ganhteamgg123}"]
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      restart: always
      
    backend:
      # Sử dụng image từ Docker Hub thay vì build local
      image: ${DOCKER_USERNAME:-thanhvinh200804}/pixoria-backend:latest
      restart: always
      environment:
        - DEBUG=0
        - DJANGO_ALLOWED_HOSTS=*,localhost,${DOMAIN_OR_IP}
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_HOST=redis-server
        - REDIS_PORT=6379
        - REDIS_PASSWORD=${REDIS_PASSWORD:-ganhteamgg123}
        - REDIS_DB=0
        - AWS_USE_S3=${AWS_USE_S3:-False}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_STORAGE_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
        - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      volumes:
        - ./mediafiles:/app/mediafiles
        - ./staticfiles:/app/staticfiles
        - ./clip_cache:/root/.cache/clip
      ports:
        - "8000:8000"
      depends_on:
        - redis-server

    frontend:
      # Sử dụng image từ Docker Hub thay vì build local
      image: ${DOCKER_USERNAME:-thanhvinh200804}/pixoria-frontend:latest
      restart: always
      environment:
        - NEXT_PUBLIC_API_URL=https://${DOMAIN_OR_IP}/api
        - NEXT_PUBLIC_API_BASE_URL=https://${DOMAIN_OR_IP}/api
        - NODE_ENV=production
      ports:
        - "3000:3000"
      depends_on:
        - backend

    nginx:
      image: nginx:alpine
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./ssl:/etc/nginx/ssl
        - ./staticfiles:/static
        - ./mediafiles:/media
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend
        - frontend
      restart: always

  volumes:
    redis-data:
    clip-cache:

  # Hướng dẫn sử dụng:
  # 1. Sao chép file này vào máy chủ triển khai
  # 2. Thiết lập các biến môi trường sau trước khi chạy:
  #    - export DOCKER_USERNAME="your-dockerhub-username"
  #    - export DATABASE_URL="your-database-url"
  #    - export DOMAIN_OR_IP="your-domain-or-ip"
  #    - export REDIS_PASSWORD="your-redis-password"
  #    - export AWS_USE_S3="True" (nếu bạn muốn sử dụng S3)
  #    - export AWS_ACCESS_KEY_ID="your-aws-key"
  #    - export AWS_SECRET_ACCESS_KEY="your-aws-secret"
  #    - export AWS_STORAGE_BUCKET_NAME="your-bucket-name"
  #    - export AWS_S3_REGION_NAME="your-region"
  # 3. Chạy: docker-compose -f docker-compose.production.yml up -d