# version: '3.8'

services:
  redis-server:
    image: redis:latest
    command: ["redis-server", "--requirepass", "ganhteamgg123"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./webImage
      dockerfile: Dockerfile
    env_file:
      - ./webImage/.env
    volumes:
      - ./webImage:/app
      - clip-cache:/root/.cache/clip
    # Loại bỏ ports vì Nginx sẽ xử lý proxy
    depends_on:
      - redis-server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    # Loại bỏ ports vì Nginx sẽ xử lý proxy
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  redis-data:
  clip-cache: