# Generated by Django 5.1.6 on 2025-02-18 01:39

import django.db.models.deletion
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('social_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='file_url',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=media.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='media.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media.user'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
