# Generated by Django 4.2.19 on 2025-03-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecategory',
            options={'ordering': ['id']},
        ),
    ]
