# Generated by Django 4.2.19 on 2025-03-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_imagecategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='media.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_images', to='media.userprofile')),
            ],
            options={
                'ordering': ['-liked_at'],
                'unique_together': {('user', 'image')},
            },
        ),
    ]
