# Generated by Django 4.2.19 on 2025-04-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_likedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_by', to='media.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_images', to='media.userprofile')),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'unique_together': {('user', 'image')},
            },
        ),
    ]
