# Generated by Django 4.2.19 on 2025-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_downloadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('download', 'Download'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
