# Generated by Django 4.2.19 on 2025-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
