# Generated by Django 4.2.19 on 2025-03-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_userprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_count',
        ),
    ]
